language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install imagick; fi'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit
